# Generated by Django 3.0.2 on 2020-02-17 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.CharField(choices=[('True', True), ('False', False)], default='False', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('movie_dvd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvd', to='movie.movie')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dvd_orders', to='dvd.Order')),
                ('user_dvd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dvd_form', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
