# Generated by Django 3.0.2 on 2020-02-17 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvd', '0002_remove_dvd_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvd',
            name='movie_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dvd_orders', to='dvd.Order'),
        ),
    ]
